<template>
	<el-container>
		<!-- <el-header>
			<tzu-header />
		</el-header> -->
		<el-main>
			<tzu-card size="fluid" :data="userData">
				<template #action>
					<el-button type="primary">测试按钮</el-button>
				</template>
				<el-table
					border
					class="tzu-table"
					:data="scoreData"
					height="100%"
					row-class-name="tzu-table-row"
					header-row-class-name="tzu-table-row"
				>
					<el-table-column
						:prop="item.prop"
						:label="item.label"
						header-align="center"
						v-for="(item, index) in tableConfig"
					></el-table-column>
				</el-table>
			</tzu-card>
			<!-- <router-view /> -->
		</el-main>
	</el-container>
</template>

<script>
import Card from './components/Card.vue';
export default {
	// 引入组件
	components: {
		tzuCard: () => import('@/components/Card'),
		tzuHeader: () => import('@/components/Header'),
	},
	// 数据初始化
	data() {
		return {
			userData: {
				name: '张三',
				sex: 1,
				id: 223322333,
				department: '计算机科学与技术学院',
				specialty: '计算机科学与技术（苏软嵌入）',
				class: '17 计科（嵌入）1 班',
			},
			scoreData: [
				{
					semester: '2018-2019学年第一学期',
					course: '[24011007]数学逻辑电路',
					category: '专业基础课/必修课',
					credit: 2.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 0,
					midExamResult: 0,
					lastExamResult: 0,
					skillMode: '实验',
					skillResult: 87.0,
					results: '优秀',
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
				{
					semester: '2019-2020学年第一学期',
					course: '[24012130]MapReduce基础（E）',
					category: '专业课/必修课',
					credit: 3.0,
					examinationMode: '考试',
					studyMode: '初修',
					usuallyExamResult: 96.0,
					midExamResult: 85.0,
					lastExamResult: 60.0,
					skillMode: '实验',
					skillResult: 87.0,
					results: 71.4,
					remarks: '',
				},
			],
			tableConfig: [
				{
					prop: 'semester',
					label: '学年学期',
				},
				{
					prop: 'course',
					label: '课程/环节',
				},
				{
					prop: 'category',
					label: '类别',
				},
				{
					prop: 'credit',
					label: '学分',
				},
				{
					prop: 'examinationMode',
					label: '考核方式',
				},
				{
					prop: 'studyMode',
					label: '修读性质',
				},
				{
					prop: 'usuallyExamResult',
					label: '平时成绩',
				},
				{
					prop: 'midExamResult',
					label: '中考成绩',
				},
				{
					prop: 'lastExamResult',
					label: '末考成绩',
				},
				{
					prop: 'skillMode',
					label: '类别',
				},
				{
					prop: 'skillResult',
					label: '成绩',
				},
				{
					prop: 'results',
					label: '综合成绩',
				},
				{
					prop: '',
					label: '辅修标记',
				},
				{
					prop: 'remarks',
					label: '备注',
				},
			],
		};
	},
};
</script>
